# permissions for end users to edit postgrests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgrest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgrest-operator
    app.kubernetes.io/part-of: postgrest-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrest-editor-role
rules:
- apiGroups:
  - postgrest.postgrest.digitalhub
  resources:
  - postgrests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgrest.postgrest.digitalhub
  resources:
  - postgrests/status
  verbs:
  - get
