# permissions for end users to view postgrests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgrest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgrest-operator
    app.kubernetes.io/part-of: postgrest-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrest-viewer-role
rules:
- apiGroups:
  - operator.postgrest.org
  resources:
  - postgrests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.postgrest.org
  resources:
  - postgrests/status
  verbs:
  - get
