apiVersion: operator.postgrest.org/v1
kind: Postgrest
metadata:
  name: cr2
  namespace: postgrest-operator-system
spec:
  schema: operator
  tables:
    - test
  anonRole:
  grants: SELECT, UPDATE, INSERT, DELETE
  connection:
    host: 192.168.178.120
    port: 5432
    database: postgres
    user:
    password:
    extraParams: sslmode=disable
    secretName: mysecret