apiVersion: operator.postgrest.org/v1
kind: Postgrest
metadata:
  name: cr2
  namespace: postgrest-operator-system
spec:
  schema: operator
  tables:
    - test
  anonRole:
  grants: SELECT, UPDATE, INSERT, DELETE