apiVersion: postgrest.postgrest.digitalhub/v1
kind: Postgrest
metadata:
  name: cr2
  namespace: postgrest-operator-system
spec:
  schemas: operator
  tables:
    - operator.test
  anonRole:
  grants: SELECT, UPDATE, INSERT, DELETE